-- 01_create_tables_supabase.sql
-- Run this in Supabase SQL Editor.
-- Supabase uses PostgreSQL, not MySQL.

-- Optional but useful for case-insensitive uniqueness later.
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- ─────────────────────────────────────────────
-- 1. SITE MASTER TABLE
-- ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS sites (
    site_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_name TEXT NOT NULL UNIQUE,
    site_code VARCHAR(50) UNIQUE,
    commission_date DATE,
    dc_kw NUMERIC(12, 2),
    ac_kw NUMERIC(12, 2),
    manufacturer TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ─────────────────────────────────────────────
-- 2. METADATA RULEBOOK TABLE
-- One row per Site + Inverter + MPPT rule.
-- ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS metadata_rulebook (
    metadata_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id BIGINT NOT NULL REFERENCES sites(site_id) ON DELETE CASCADE,
    inverter_name TEXT NOT NULL,
    mppt_no INTEGER NOT NULL,
    strings_per_mppt INTEGER,
    modules_per_string INTEGER,
    total_modules INTEGER,
    module_wattage NUMERIC(12, 2),
    dc_load_kw NUMERIC(12, 2),
    tilt_degrees NUMERIC(6, 2),
    azimuth_degrees NUMERIC(6, 2),
    mppt_v_min NUMERIC(10, 2),
    mppt_v_max NUMERIC(10, 2),
    manufacturer TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE (site_id, inverter_name, mppt_no)
);

-- ─────────────────────────────────────────────
-- 3. UPLOAD BATCH TABLE
-- One row for each uploaded/processed file.
-- ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS upload_batch (
    upload_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_name TEXT NOT NULL,
    file_type TEXT NOT NULL, -- metadata / daily_raw
    uploaded_by TEXT,
    storage_path TEXT,
    loaded_at TIMESTAMPTZ DEFAULT NOW(),
    status TEXT DEFAULT 'loading', -- loading / completed / failed
    remarks TEXT
);

-- ─────────────────────────────────────────────
-- 4. RAW DAILY STAGING TABLE
-- Temporary/working table. Keep rows by upload_id.
-- Do not rely on this as the permanent history table.
-- ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS raw_daily_staging (
    staging_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    upload_id BIGINT REFERENCES upload_batch(upload_id) ON DELETE CASCADE,
    row_no INTEGER,
    raw_site_id TEXT,
    site_name TEXT,
    hw_id TEXT,
    inverter_name TEXT,
    reading_date DATE,
    has_rsds BOOLEAN,
    idc_total NUMERIC(14, 4),
    idc_1 NUMERIC(14, 4),
    idc_2 NUMERIC(14, 4),
    idc_3 NUMERIC(14, 4),
    idc_4 NUMERIC(14, 4),
    idc_5 NUMERIC(14, 4),
    idc_6 NUMERIC(14, 4),
    vdc_avg NUMERIC(14, 4),
    vdc_1 NUMERIC(14, 4),
    vdc_2 NUMERIC(14, 4),
    vdc_3 NUMERIC(14, 4),
    vdc_4 NUMERIC(14, 4),
    vdc_5 NUMERIC(14, 4),
    vdc_6 NUMERIC(14, 4),
    loaded_at TIMESTAMPTZ DEFAULT NOW()
);

-- ─────────────────────────────────────────────
-- 5. RAW DAILY HISTORY TABLE
-- Permanent raw backup of the original daily rows.
-- ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS raw_daily_history (
    raw_history_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    upload_id BIGINT REFERENCES upload_batch(upload_id) ON DELETE SET NULL,
    row_no INTEGER,
    raw_site_id TEXT,
    site_name TEXT,
    hw_id TEXT,
    inverter_name TEXT,
    reading_date DATE,
    has_rsds BOOLEAN,
    idc_total NUMERIC(14, 4),
    idc_1 NUMERIC(14, 4),
    idc_2 NUMERIC(14, 4),
    idc_3 NUMERIC(14, 4),
    idc_4 NUMERIC(14, 4),
    idc_5 NUMERIC(14, 4),
    idc_6 NUMERIC(14, 4),
    vdc_avg NUMERIC(14, 4),
    vdc_1 NUMERIC(14, 4),
    vdc_2 NUMERIC(14, 4),
    vdc_3 NUMERIC(14, 4),
    vdc_4 NUMERIC(14, 4),
    vdc_5 NUMERIC(14, 4),
    vdc_6 NUMERIC(14, 4),
    loaded_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE (upload_id, row_no)
);

-- ─────────────────────────────────────────────
-- 6. DAILY VALIDATED DATA TABLE
-- Permanent clean/final history for dashboard.
-- ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS daily_validated_data (
    validated_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id BIGINT REFERENCES sites(site_id) ON DELETE SET NULL,
    raw_site_id TEXT,
    site_name TEXT NOT NULL,
    hw_id TEXT NOT NULL,
    inverter_name TEXT NOT NULL,
    reading_date DATE NOT NULL,
    has_rsds BOOLEAN,
    idc_total NUMERIC(14, 4),
    idc_1 NUMERIC(14, 4),
    idc_2 NUMERIC(14, 4),
    idc_3 NUMERIC(14, 4),
    idc_4 NUMERIC(14, 4),
    idc_5 NUMERIC(14, 4),
    idc_6 NUMERIC(14, 4),
    vdc_avg NUMERIC(14, 4),
    vdc_1 NUMERIC(14, 4),
    vdc_2 NUMERIC(14, 4),
    vdc_3 NUMERIC(14, 4),
    vdc_4 NUMERIC(14, 4),
    vdc_5 NUMERIC(14, 4),
    vdc_6 NUMERIC(14, 4),
    source_upload_id BIGINT REFERENCES upload_batch(upload_id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE (site_name, hw_id, inverter_name, reading_date)
);

-- ─────────────────────────────────────────────
-- 7. VALIDATION ISSUES TABLE
-- Stores errors and warnings from validation.
-- ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS validation_issues (
    issue_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    upload_id BIGINT REFERENCES upload_batch(upload_id) ON DELETE CASCADE,
    row_no INTEGER,
    site_id BIGINT REFERENCES sites(site_id) ON DELETE SET NULL,
    site_name TEXT,
    hw_id TEXT,
    inverter_name TEXT,
    reading_date DATE,
    mppt_no INTEGER,
    issue_type TEXT NOT NULL,
    severity TEXT NOT NULL, -- error / warning / info
    issue_message TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ─────────────────────────────────────────────
-- EXTRA CONFIG TABLES FOR FRONTEND EDITING
-- ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS site_alias (
    alias_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    raw_site_name TEXT NOT NULL UNIQUE,
    site_id BIGINT NOT NULL REFERENCES sites(site_id) ON DELETE CASCADE,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS inverter_alias (
    alias_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id BIGINT NOT NULL REFERENCES sites(site_id) ON DELETE CASCADE,
    raw_inverter_name TEXT NOT NULL,
    metadata_inverter_name TEXT NOT NULL,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE (site_id, raw_inverter_name)
);

CREATE TABLE IF NOT EXISTS validation_rule_config (
    rule_name TEXT PRIMARY KEY,
    severity TEXT NOT NULL DEFAULT 'error',
    is_active BOOLEAN DEFAULT TRUE,
    description TEXT,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

INSERT INTO validation_rule_config (rule_name, severity, is_active, description)
VALUES
    ('SITE_NOT_FOUND', 'error', TRUE, 'Site from raw daily file is not found in sites or site_alias.'),
    ('INVERTER_NOT_FOUND', 'error', TRUE, 'Inverter from raw daily file is not found in metadata or inverter_alias.'),
    ('MISSING_DATE', 'error', TRUE, 'Reading date is missing or invalid.'),
    ('MISSING_REQUIRED_VALUE', 'error', TRUE, 'Important required raw value is missing.'),
    ('NEGATIVE_VALUE', 'error', TRUE, 'IDC or VDC value is negative.'),
    ('VDC_OUT_OF_RANGE', 'warning', TRUE, 'VDC value is outside MPPT voltage range.')
ON CONFLICT (rule_name) DO NOTHING;

-- Helpful indexes
CREATE INDEX IF NOT EXISTS idx_staging_upload ON raw_daily_staging(upload_id);
CREATE INDEX IF NOT EXISTS idx_history_upload ON raw_daily_history(upload_id);
CREATE INDEX IF NOT EXISTS idx_validated_date ON daily_validated_data(reading_date);
CREATE INDEX IF NOT EXISTS idx_issues_upload ON validation_issues(upload_id);
CREATE INDEX IF NOT EXISTS idx_issues_severity ON validation_issues(severity);
CREATE INDEX IF NOT EXISTS idx_metadata_site_inv ON metadata_rulebook(site_id, inverter_name);
